name: Main branch build, test, and publish

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/build-and-test.yml


  package_publish:
    needs: test
    uses: ./.github/workflows/publish.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  helm_publish:
    needs: package_publish
    uses: ./.github/workflows/release.yml
    secrets:
      CR_TOKEN: ${{ secrets.GH_ACTIONS_ACCESS_TOKEN }}
